# Project information
site_name: 'Branch documentation'
site_description: 'Branch Documentation for Deep Linking'
site_author: 'Branch'
site_url: 'https://ethanneff.github.io/branch-docs'

# Repository
repo_name: 'Branch Documentation'
repo_url: 'https://github.com/ethanneff/branch-docs'
edit_uri: 'edit/master/src/docs/'

# Copyright
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'

# Files
theme: 'material'
theme_dir: 'lib/mkdocs-material/material'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/main.js'
site_favicon: img/favicon-96x96.png

# Options
extra:
  # logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-2'

# Extensions
markdown_extensions:
  - codehilite(linenums=true)
  - footnotes
  - toc(permalink=true)
  - meta
  - pymdownx.github
  - markdown_include.include

# Pages
pages:
  - Features: index.md
  - Getting started:
    - iOS: docs/getting-started/ios.md
    - Android: docs/getting-started/android.md
    - Adobe AIR: docs/getting-started/adobe-air.md
    - Cordova PhoneGap Ionic: docs/getting-started/cordova-phonegap-ionic.md
    - iMessage: docs/getting-started/imessage.md
    - mParticle Android: docs/getting-started/mparticle-android.md
    - mParticle iOS: docs/getting-started/mparticle-ios.md
    - Titanium: docs/getting-started/titanium.md
    - React Native: docs/getting-started/react-native.md
    - Unity: docs/getting-started/unity.md
    - Xamarin: docs/getting-started/xamarin.md
  - Configuring links:
    - Understanding links: docs/managing-links/understand-links.md
    - Creating links: docs/managing-links/create-links.md
  - Converting web to app:
    - Deep Views: docs/web-to-app/deep-views.md
    - Text me the app: docs/web-to-app/text-me-the-app.md
    - Journeys: docs/web-to-app/journeys.md
  - Converting ads to app:
    - Deep Link Feeds: docs/ads-to-app/deep-link-feeds.md
    - App Install Ads: docs/ads-to-app/app-install-ads.md
    - Google App Installs: docs/ads-to-app/google-app-installs.md
    - Google Universal App Campaigns: docs/ads-to-app/google-universal-app-campaigns.md
    - Google Search Ads: docs/ads-to-app/google-search.md
    - Facebook App Installs: docs/ads-to-app/facebook-app-installs.md
    - Facebook App Engagement: docs/ads-to-app/facebook-app-engagement.md
    - Facebook Instagram: docs/ads-to-app/facebook-instagram.md
    - Pinterets App Installs: docs/ads-to-app/pinterest-app-installs.md
    - Snapchat App Installs: docs/ads-to-app/snapchat-app-installs.md
  - Converting emails to app:
    - Responsys: docs/emails-to-app/responsys.md
    - SFMC: docs/emails-to-app/sfmc.md
    - SendGrid: docs/emails-to-app/sendgrid.md
    - Sailthru: docs/emails-to-app/sailthru.md
    - AppBoy: docs/emails-to-app/appboy.md
    - Self Serve: docs/emails-to-app/self-serve.md
  - Tracking analytics:
    - Growth: docs/track-analytics/growth-attribution.md
    - User Value: docs/track-analytics/user-value attribution.md
    - Revenue: docs/track-analytics/revenue-attribution.md
  - Exporting analytics:
    - CSV Export: docs/export-analytics/export-csv.md
    - Export API: docs/export-analytics/export-api.md
    - Webhooks: docs/export-analytics/export-webhooks.md
  - Integrating analytics:
    - Abobe Analytics: docs/integrate-analytics/abobe-analytics.md
    - Adjust: docs/integrate-analytics/adjust.md
    - Amplitude: docs/integrate-analytics/amplitude.md
    - AppBoy: docs/integrate-analytics/appboy.md
    - Google Analytics: docs/integrate-analytics/google-analytics.md
    - Kochava: docs/integrate-analytics/kochava.md
    - Localytics: docs/integrate-analytics/localytics.md
    - Mixpanel: docs/integrate-analytics/mixpanel.md
    - Tune: docs/integrate-analytics/tune.md
    - AppMetrica: docs/integrate-analytics/appmetrica.md