# Project information
site_name: 'Branch documentation'
site_description: 'Branch Documentation for Deep Linking'
site_author: 'Branch'
site_url: 'https://branchmetrics.github.io/ddocs'

# Repository
repo_name: 'Branch Documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/src/'

# Copyright
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'

# Files
theme: 'material'
theme_dir: 'lib/mkdocs-material/material'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/main.js'
site_favicon: img/favicon-96x96.png

# Options
extra:
  # logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-docs'

# Extensions
markdown_extensions:
  - codehilite #(linenums=true)
  - footnotes
  - toc(permalink=true)
  - meta
  - pymdownx.github
  - markdown_include.include

# Pages
pages:
  - Features: index.md
  - Configure your app:
    - iOS: pages/getting-started/ios.md
    - Android: pages/getting-started/android.md
    - Adobe AIR: pages/getting-started/adobe-air.md
    - Cordova PhoneGap Ionic: pages/getting-started/cordova-phonegap-ionic.md
    - iMessage: pages/getting-started/imessage.md
    - mParticle Android: pages/getting-started/mparticle-android.md
    - mParticle iOS: pages/getting-started/mparticle-ios.md
    - Titanium: pages/getting-started/titanium.md
    - React Native: pages/getting-started/react-native.md
    - Unity: pages/getting-started/unity.md
    - Xamarin: pages/getting-started/xamarin.md
  - Configure your website:
    - Deep Views: pages/web-to-app/deep-views.md
    - Text me the app: pages/web-to-app/text-me-the-app.md
    - Journeys: pages/web-to-app/journeys.md
  - Configure your links:
    - Understanding links: pages/configuring-links/understand-links.md
    - Creating links: pages/configuring-links/create-links.md
  - Configure your ads:
    - Deep Link Feeds: pages/ads-to-app/deep-link-feeds.md
    - App Install Ads: pages/ads-to-app/app-install-ads.md
    - Google App Installs: pages/ads-to-app/google-app-installs.md
    - Google Universal App Campaigns: pages/ads-to-app/google-universal-app-campaigns.md
    - Google Search Ads: pages/ads-to-app/google-search.md
    - Facebook App Installs: pages/ads-to-app/facebook-app-installs.md
    - Facebook App Engagement: pages/ads-to-app/facebook-app-engagement.md
    - Facebook Instagram: pages/ads-to-app/facebook-instagram.md
    - Pinterets App Installs: pages/ads-to-app/pinterest-app-installs.md
    - Snapchat App Installs: pages/ads-to-app/snapchat-app-installs.md
  - Configure your emails:
    - Responsys: pages/emails-to-app/responsys.md
    - SFMC: pages/emails-to-app/sfmc.md
    - SendGrid: pages/emails-to-app/sendgrid.md
    - Sailthru: pages/emails-to-app/sailthru.md
    - AppBoy: pages/emails-to-app/appboy.md
    - Self Serve: pages/emails-to-app/self-serve.md
  - Track your analytics:
    - Growth: pages/track-analytics/growth-attribution.md
    - User Value: pages/track-analytics/user-value attribution.md
    - Revenue: pages/track-analytics/revenue-attribution.md
  - Export your analytics:
    - CSV Export: pages/export-analytics/export-csv.md
    - Export API: pages/export-analytics/export-api.md
    - Webhooks: pages/export-analytics/export-webhooks.md
  - Integrate your analytics:
    - Abobe Analytics: pages/integrate-analytics/abobe-analytics.md
    - Adjust: pages/integrate-analytics/adjust.md
    - Amplitude: pages/integrate-analytics/amplitude.md
    - AppBoy: pages/integrate-analytics/appboy.md
    - Google Analytics: pages/integrate-analytics/google-analytics.md
    - Kochava: pages/integrate-analytics/kochava.md
    - Localytics: pages/integrate-analytics/localytics.md
    - Mixpanel: pages/integrate-analytics/mixpanel.md
    - Tune: pages/integrate-analytics/tune.md
    - AppMetrica: pages/integrate-analytics/appmetrica.md