# Project
site_name: 'Branch documentation'
site_description: 'Branch documentation for mobile deep linking'
site_author: 'Branch'
site_url: 'https://branchmetrics.github.io/docs'
repo_name: 'Branch documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/src/'
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'
site_favicon: img/favicon-96x96.png

# Files
theme: 'material'
theme_dir: 'lib/mkdocs-material/material'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/router.js'
  - 'js/events.js'
  - 'js/modals.js'
  - 'js/images.js'
  - 'js/buttons.js'
  - 'js/analytics.js'
  - 'js/tabs.js'
  - 'js/languages.js'
  - 'js/utils.js'
  - 'js/main.js'

# Extensions
markdown_extensions:
  - admonition:
  - codehilite: #(linenums=true)
  - footnotes:
  - toc(permalink=true):
  - meta:
  - pymdownx.github:
  - attr_list:
  - markdown_include.include:
      base_path: src/includes/

# Options
extra:
  logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-docs'
  google_optimize:
    optimize: 'GTM-PCPBXCN'
    analytics: 'UA-98205710-1'
  algolia_docsearch:
    apiKey: '887017d17a2c1e9490ad2c44caa7e817'
    indexName: 'branchmetrics'
    inputSelector: '#algolia-doc-search'
    debug: true
    hits: 15
  mixpanel:
    apiKey: '47ec8ea9ac102b1370221dcda476091c'
  nav_header:
    - index: 2
      title: Basic deep linking
    - index: 7
      title: Advanced deep linking
    - index: 14
      title: Resources
  nav_hidden:
    - 'Google Search App Install Ads'
    - 'Google Search App Engagement Ads'
    - 'Google Display App Install Ads'
    - 'Google Display App Engagement Ads'
    - 'Google Universal App Campaigns'
    - 'Google Search Network Ads'
    - 'Google Display Network Ads'
    - 'Google Adwords Conversion Setup'
    - 'Google Video Ads'
    - 'Facebook App Install Ads'
    - 'Facebook Traffic and Conversion Ads'
    - 'Facebook Platform Ads'
    - 'Facebook Dynamic Ads'
  is_visible:
    footer_floater_beta: true
    footer_floater_old_docs: true
    footer_nav: false
    header_git: false
    header_breadcrumb: true

# Pages
pages:
  - Getting started: index.md
  - Setup your dashboard: pages/dashboard/integrate.md
  - Setup your app:
    - iOS: pages/apps/ios.md
    - Android: pages/apps/android.md
    - Adobe AIR: pages/apps/adobe-air.md
    - Cordova PhoneGap Ionic: pages/apps/cordova-phonegap-ionic.md
    - mParticle Android: pages/apps/mparticle-android.md
    - mParticle iOS: pages/apps/mparticle-ios.md
    - Titanium: pages/apps/titanium.md
    - React Native: pages/apps/react-native.md
    - Unity: pages/apps/unity.md
    - Xamarin: pages/apps/xamarin.md
    - API: pages/apps/api.md
  - Setup your website: pages/web/integrate.md
  - Create deep links: pages/links/integrate.md
  - Track analytics: pages/dashboard/analytics.md
  - Deep link web:
    - Deepviews: pages/web/deep-views.md
    - Journeys App Banners: pages/web/journeys.md
    - AMP Journeys: pages/web/amp-journeys.md
    - Text Me The App: pages/web/text-me-the-app.md
  - Deep link ads:
    - Dynamic Product Feeds: pages/deep-linked-ads/dynamic-product-feeds.md
    - Branch Universal Ads: pages/deep-linked-ads/branch-universal-ads.md
    - Apple Search: pages/deep-linked-ads/apple.md
    - Doubleclick: pages/deep-linked-ads/doubleclick.md
    - Google: pages/deep-linked-ads/google-ads-overview.md
    - Google Search App Install Ads: pages/deep-linked-ads/google-search-install-ads.md
    - Google Search App Engagement Ads: pages/deep-linked-ads/google-search-engagement-ads.md
    - Google Display App Install Ads: pages/deep-linked-ads/google-display-install-ads.md
    - Google Display App Engagement Ads: pages/deep-linked-ads/google-display-engagement-ads.md
    - Google Universal App Campaigns: pages/deep-linked-ads/google-uac.md
    - Google Search Network Ads: pages/deep-linked-ads/google-xplatform-search-ads.md
    - Google Display Network Ads: pages/deep-linked-ads/google-xplatform-display-ads.md
    - Google Adwords Conversion Setup: pages/deep-linked-ads/google-conversions.md
    - Google Video Ads: pages/deep-linked-ads/google-video-ads.md
    - Facebook: pages/deep-linked-ads/facebook-ads-overview.md
    - Facebook App Install Ads: pages/deep-linked-ads/facebook-app-install-ads.md
    - Facebook Traffic and Conversion Ads: pages/deep-linked-ads/facebook-traffic-conversion-ads.md
    - Facebook Platform Ads: pages/deep-linked-ads/facebook-platform-ads.md
    - Facebook Dynamic Ads: pages/deep-linked-ads/facebook-dynamic-ads.md
    - Twitter: pages/deep-linked-ads/twitter.md
  - Deep link emails:
    - Appboy: pages/emails/appboy.md
    - Blueshift: pages/emails/blueshift.md
    - Epsilon: pages/emails/epsilon.md
    - MailGun: pages/emails/mailgun.md
    - PostUp: pages/emails/postup.md
    - Responsys: pages/emails/responsys.md
    - Sailthru: pages/emails/sailthru.md
    - Salesforce: pages/emails/salesforce.md
    - SendGrid: pages/emails/sendgrid.md
    - Zeta: pages/emails/zeta.md
    - Self Serve: pages/emails/self-serve.md
  - Deep link organic search:
    - Firebase: pages/organic-search/firebase.md
    - Spotlight: pages/organic-search/spotlight.md
  - Deep link apps:
    - Android Instant Apps: pages/app-to-app/android-instant-apps.md
    - iMessage Apps: pages/app-to-app/imessage-apps.md
    - Facebook App Invites: pages/app-to-app/facebook-app-invites.md
  - Export analytics:
    - Export API: pages/exports/api.md
    - Webhooks: pages/exports/webhooks.md
  - Integrate third party platforms:
    - Abobe Analytics: pages/integrations/adobe-analytics.md
    - Adjust: pages/integrations/adjust.md
    - Amplitude: pages/integrations/amplitude.md
    - AppMetrica: pages/integrations/appmetrica.md
    - Appboy: pages/integrations/appboy.md
    - Appsflyer: pages/integrations/appsflyer.md
    - Fabric Answers: pages/integrations/fabric-answers.md
    - Google Analytics: pages/integrations/google-analytics.md
    - Kochava: pages/integrations/kochava.md
    - Localytics: pages/integrations/localytics.md
    - Mixpanel: pages/integrations/mixpanel.md
    - Tune: pages/integrations/tune.md
  - Validation Tools: pages/resources/validation-tools.md
  - Case Studies and Infographics: pages/resources/case-studies.md
