# Project
site_name: 'Branch Documentation'
site_description: 'Branch Documentation for Deep Linking'
site_author: 'Branch'
site_url: 'https://branchmetrics.github.io/docs'
repo_name: 'Branch Documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/src/'
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'

# Files
theme: 'material'
theme_dir: 'lib/mkdocs-material/material'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/main.js'
site_favicon: img/favicon-96x96.png

# Options
extra:
  # logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-docs'
  google_optimize:
    optimize: 'GTM-PDHLH8M'
    analytics: 'UA-98205710-1'
  algolia_docsearch:
    apiKey: '887017d17a2c1e9490ad2c44caa7e817'
    indexName: 'branchmetrics'
    inputSelector: '#algolia-doc-search'
    debug: true
    hits: 15
  mixpanel:
    apiKey: '47ec8ea9ac102b1370221dcda476091c'
  nav_headers:
    - index: 2
      title: Basic deep linking
    - index: 6
      title: Advance deep linking

# Extensions
markdown_extensions:
  - admonition:
  - codehilite: #(linenums=true)
  - footnotes:
  - toc(permalink=true):
  - meta:
  - pymdownx.github:
  - attr_list:
  - markdown_include.include:
      base_path: src/includes/

# Pages hidden from nav bar
extra:
  hidden_pages: [""]

# Pages
pages:
  - Getting started: index.md
  - Integate your app:
    - iOS: pages/apps/ios.md
    - Android: pages/apps/android.md
    - Adobe AIR: pages/apps/adobe-air.md
    - Cordova PhoneGap Ionic: pages/apps/cordova-phonegap-ionic.md
    - mParticle Android: pages/apps/mparticle-android.md
    - mParticle iOS: pages/apps/mparticle-ios.md
    - Titanium: pages/apps/titanium.md
    - React Native: pages/apps/react-native.md
    - Unity: pages/apps/unity.md
    - Xamarin: pages/apps/xamarin.md
    - API: pages/apps/api.md
  - Integrate your website:
    - Setup: pages/web/setup.md
    - Deepviews: pages/web/deep-views.md
    - Journeys App Banners: pages/web/journeys.md
    - Text Me The App: pages/web/text-me-the-app.md
  - Create deep links:
    - Link behavior: pages/links/behavior.md
    - Link data: pages/links/data.md
    - Link domain: pages/links/link-domain.md
    - Creating links: pages/links/create.md
  - Track analytics:
    - Behavior: pages/analytics/behavior.md
    - Referrals: pages/analytics/referrals.md
    - Growth: pages/analytics/growth-attribution.md
    - User Value: pages/analytics/user-value attribution.md
    - Revenue: pages/analytics/revenue-attribution.md
  - Deep link ads:
    - Apple Search Ads: pages/ads/apple.md
    - Dynamic Product Feeds: pages/ads/dynamic-product-feeds.md
    - Branch Universal Ads: pages/ads/branch-universal-ads.md
    - Doubleclick: pages/ads/doubleclick.md
    - Google App Installs: pages/ads/google-app-installs.md
    - Google Universal App Campaigns: pages/ads/google-universal-app-campaigns.md
    - Google Search Ads: pages/ads/google-search.md
    - Facebook App Installs: pages/ads/facebook-app-installs.md
    - Facebook App Engagement: pages/ads/facebook-app-engagement.md
    - Facebook Instagram: pages/ads/facebook-instagram.md
    - Twitter Ads: pages/ads/twitter.md
  - Deep link emails:
    - Responsys: pages/emails/responsys.md
    - SFMC: pages/emails/sfmc.md
    - SendGrid: pages/emails/sendgrid.md
    - Sailthru: pages/emails/sailthru.md
    - AppBoy: pages/emails/appboy.md
    - Self Serve: pages/emails/self-serve.md
  - Deep link organic search:
    - Firebase: pages/organic-search/firebase.md
    - Spotlight: pages/organic-search/spotlight.md
  - Deep link apps:
    - Android Instant Apps: pages/app-to-app/android-instant-apps.md
    - iMessage Apps: pages/app-to-app/imessage-apps.md
    - Facebook App Invites: pages/app-to-app/facebook-app-invites.md
  - Export analytics:
    - CSV Export: pages/exports/csv.md
    - Export API: pages/exports/api.md
    - Webhooks: pages/exports/webhooks.md
  - Integrate analytics:
    - Abobe Analytics: pages/integrations/abobe-analytics.md
    - Adjust: pages/integrations/adjust.md
    - Amplitude: pages/integrations/amplitude.md
    - AppBoy: pages/integrations/appboy.md
    - Google Analytics: pages/integrations/google-analytics.md
    - Kochava: pages/integrations/kochava.md
    - Localytics: pages/integrations/localytics.md
    - Mixpanel: pages/integrations/mixpanel.md
    - Tune: pages/integrations/tune.md
    - AppMetrica: pages/integrations/appmetrica.md
