# Project information
site_name: 'Branch Documentation'
site_description: 'Branch Documentation for Deep Linking'
site_author: 'Branch'
site_url: 'https://ethanneff.github.io/branch-docs'

# Repository
repo_name: 'Branch Documentation'
repo_url: 'https://github.com/ethanneff/branch-docs'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'

# Files
theme: 'material'
theme_dir: 'src'
docs_dir: 'src/docs'
extra_css:
  - 'css/analytics.css'
  - 'css/main.css'

extra_javascript:
  - 'js/analytics.js'
  - 'js/main.js'

# Options
extra:
  # logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'

# Extensions
markdown_extensions:
  - codehilite
  - footnotes
  - toc
  - meta
  - pymdownx.github
  - markdown_include.include

# Pages
pages:
  - Features: index.md
  - Getting started:
    - iOS:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - Android:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/android/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - Adobe AIR:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - Cordova PhoneGap Ionic:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/cordova-phonegap-ionic/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - iMessage:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - mParticle Android:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - mParticle iOS:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - React Native:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - Titanium:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - Unity:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
    - Xamerian:
      - Deep link into your app: app/ios/deeplink.md
      - Create links: app/ios/createlink.md
      - Share links: app/ios/sharelink.md
      - Navigate to content: app/ios/navigatelink.md
      - Track custom events: app/ios/trackevent.md
      - Track and refer users: app/ios/trackuser.md
      - Track and publicize content: app/ios/trackcontent.md
      - Increase matching success: app/ios/matchsuccess.md
  - Tracking analytics:
    - Attribution:
      - Growth: other.md
      - User Value: other.md
    - Analytics:
      - Revenue Analytics: other.md
      - Ads Analytics (Soon): other.md
      - Email Analytics (Soon): other.md
      - … Analytics (Soon): other.md
    - Export your data:
      - CSV Export: other.md
      - Export API: other.md
      - Webhooks: other.md
    - Integrate with third parties:
      - Abobe Analytics: other.md
      - Adjust: other.md
      - Amplitude: other.md
      - AppBoy: other.md
      - Google Analytics: other.md
      - Kochava: other.md
      - Localytics: other.md
      - Mixpanel: other.md
      - Tune: other.md
      - AppMetrica: other.md
  - Web To App:
    - Deep Views: other.md
    - Text Me The App: other.md
    - Journeys: other.md
  - Ads To App:
    - Google:
      - App Installs: other.md
      - Universal App Campaigns: other.md
      - Search: other.md
    - Facebook:
      - App Installs: other.md
      - App Engagement: other.md
      - Instagram: other.md
    - Pinterest:
      - App Installs (Soon): other.md
    - Snapchat:
      - App Installs (Soon): other.md
    - Deep Link Feeds: other.md
    - App Install Ads: other.md
    - Journeys: other.md
  - Emails To App:
    - Responsys: other.md
    - SFMC: other.md
    - SendGrid: other.md
    - Sailthru: other.md
    - AppBoy: other.md
    - Self Serve: other.md
  - Apps To App:
    - iOS Roots App: other.md
    - iOS iMessage Apps: other.md
    - Android Instant Apps: other.md
