# Project information
site_name: 'Branch documentation'
site_description: 'Branch Documentation for Deep Linking'
site_author: 'Branch'
site_url: 'https://branchmetrics.github.io/docs'

# Repository
repo_name: 'Branch Documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/src/'

# Copyright
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'

# Files
theme: 'material'
theme_dir: 'lib/mkdocs-material/material'
docs_dir: 'src'
extra_css:
  - 'css/main.css'
extra_javascript:
  - 'js/main.js'
site_favicon: img/favicon-96x96.png

# Options
extra:
  # logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-docs'
  google_optimize:
    optimize: 'GTM-PDHLH8M'
    analytics: 'UA-98205710-1'
  algolia_docsearch:
    apiKey: '887017d17a2c1e9490ad2c44caa7e817'
    indexName: 'branchmetrics'
    inputSelector: '#algolia-doc-search'
    debug: true

# Extensions
markdown_extensions:
  - admonition
  - codehilite #(linenums=true)
  - footnotes
  - toc(permalink=true)
  - meta
  - pymdownx.github
  - markdown_include.include

# Pages
pages:
  - Features: index.md
  - Configure your app:
    - iOS: pages/apps/ios.md
    - Android: pages/apps/android.md
    - Adobe AIR: pages/apps/adobe-air.md
    - Cordova PhoneGap Ionic: pages/apps/cordova-phonegap-ionic.md
    - iMessage: pages/apps/imessage.md
    - mParticle Android: pages/apps/mparticle-android.md
    - mParticle iOS: pages/apps/mparticle-ios.md
    - Titanium: pages/apps/titanium.md
    - React Native: pages/apps/react-native.md
    - Unity: pages/apps/unity.md
    - Xamarin: pages/apps/xamarin.md
  - Configure your website:
    - Deepviews: pages/web/deep-views.md
    - Text me the app: pages/web/text-me-the-app.md
    - Journeys: pages/web/journeys.md
  - Configure your links:
    - Link behavior: pages/links/behavior.md
    - Link data: pages/links/data.md
    - Creating links: pages/links/create.md
  - Configure your ads:
    - Deep Link Feeds: pages/ads/deep-link-feeds.md
    - App Install Ads: pages/ads/app-install-ads.md
    - Google App Installs: pages/ads/google-app-installs.md
    - Google Universal App Campaigns: pages/ads/google-universal-app-campaigns.md
    - Google Search Ads: pages/ads/google-search.md
    - Facebook App Installs: pages/ads/facebook-app-installs.md
    - Facebook App Engagement: pages/ads/facebook-app-engagement.md
    - Facebook Instagram: pages/ads/facebook-instagram.md
    - Pinterets App Installs: pages/ads/pinterest-app-installs.md
    - Snapchat App Installs: pages/ads/snapchat-app-installs.md
  - Configure your emails:
    - Responsys: pages/emails/responsys.md
    - SFMC: pages/emails/sfmc.md
    - SendGrid: pages/emails/sendgrid.md
    - Sailthru: pages/emails/sailthru.md
    - AppBoy: pages/emails/appboy.md
    - Self Serve: pages/emails/self-serve.md
  - Track your analytics:
    - Behavior: pages/analytics/behavior.md
    - Growth: pages/analytics/growth-attribution.md
    - User Value: pages/analytics/user-value attribution.md
    - Revenue: pages/analytics/revenue-attribution.md
  - Export your analytics:
    - CSV Export: pages/exports/export-csv.md
    - Export API: pages/exports/export-api.md
    - Webhooks: pages/exports/export-webhooks.md
  - Integrate your analytics:
    - Abobe Analytics: pages/integrations/abobe-analytics.md
    - Adjust: pages/integrations/adjust.md
    - Amplitude: pages/integrations/amplitude.md
    - AppBoy: pages/integrations/appboy.md
    - Google Analytics: pages/integrations/google-analytics.md
    - Kochava: pages/integrations/kochava.md
    - Localytics: pages/integrations/localytics.md
    - Mixpanel: pages/integrations/mixpanel.md
    - Tune: pages/integrations/tune.md
    - AppMetrica: pages/integrations/appmetrica.md
