# Project
site_name: 'Branch Docs'
site_description: 'Branch documentation for mobile deep linking and attribution'
site_author: 'Branch'
repo_name: 'Branch documentation'
repo_url: 'https://github.com/branchmetrics/docs'
edit_uri: 'edit/master/pages/'
copyright: 'Copyright &copy; 2019 <a href="https://branch.io">Branch</a>'

# Files
theme:
  name: 'material'
  custom_dir: 'branch-theme'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  feature: false
  logo: '_assets/img/logo.svg'
  favicon: '_assets/img/favicon.ico'
docs_dir: 'pages'
extra_css:
  - '_assets/css/main.css'
extra_javascript:
  - '_assets/js/router.js'
  - '_assets/js/events.js'
  - '_assets/js/modals.js'
  - '_assets/js/images.js'
  - '_assets/js/buttons.js'
  - '_assets/js/progress.js'
  - '_assets/js/tabs.js'
  - '_assets/js/languages.js'
  - '_assets/js/utils.js'
  - '_assets/js/main.js'

# Extensions
markdown_extensions:
  - admonition:
  - codehilite: #(linenums=true)
  - footnotes:
  - toc:
      permalink: true
  - meta:
  - markdown.extensions.tables:
  - pymdownx.magiclink:
  - pymdownx.betterem:
  - pymdownx.tilde:
  - pymdownx.emoji:
  - pymdownx.tasklist:
  - pymdownx.superfences:
  - attr_list:
  - markdown_include.include:
      base_path: includes/

# Plugins
plugins: []

# Options
extra:
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/branchmetrics/docs'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus:
  sources:
    mixpanel: '47ec8ea9ac102b1370221dcda476091c'
    google:
      optimize: 'GTM-PCPBXCN'
      analytics: 'UA-53307642-1'
    facebook: '1040694199304729'
    munchkin: '315-FTT-121'
    linkedin: '21211'
    bizible: true
    algolia:
      key: '887017d17a2c1e9490ad2c44caa7e817'
      index: 'branchmetrics'
      selector: '#algolia-doc-search'
      debug: false
      hits: 15

# Navigation
nav:
  - Home: index.md
  - Branch Basics:
    - Overview: resources/basics-overview.md
    - Attribution:
      - Branch Matching Overview: resources/matching.md
      - People-Based Attribution: dashboard/people-based-attribution.md
    - Starting with Branch:
      - Importing Historical User Data: dashboard/importing-historical-user-data.md
      - Case Studies and Infographics: resources/case-studies.md
  - Account Settings:
    - Overview: dashboard/account-settings.md
    - Basic Settings:
      - Access Levels:
        - Overview: dashboard/access-level.md
        - Entity Views:
          - App View: dashboard/app-view.md
          - Organization View: dashboard/organization-view.md
          - Agency View: dashboard/agency-view.md
        - Resource Access:
          - App Level Access: dashboard/app-level-access.md
          - Channel Level Access: dashboard/channel-level-access.md
          - Link Level Access: dashboard/link-level-access.md
          - Sensitive Data: dashboard/sensitive-data-access.md
          - Aggregate Data: dashboard/aggregate-data-access.md
    - Advanced Settings:
      - View Billing Information: dashboard/viewing-billing.md
      - Enable Single Sign On: dashboard/sso.md
      - Changing Link Domains: dashboard/changing-link-domains.md
  - Link Settings:
    - Overview: links/branch-links-overview.md
    - Default Link Behavior Configuration: links/default-link-behavior.md
    - Advanced Settings Configuration: links/advanced-settings-configuration.md
    - Deep Link Configuration:
      - iOS Universal Links: deep-linking/universal-links.md
      - Android App Links: deep-linking/android-app-links.md
      - In-app deep link routing: deep-linking/routing.md
    - Creating Deep Links: links/integrate.md
    - Creating Quick Links: links/quick-links.md
  - Developer Resources:
    - Overview: resources/native-sdks-and-plugins.md
    - Branch SDKs & API:
      - iOS: apps/ios.md
      - Android: apps/android.md
      - Website: web/integrate.md
      - Deep Linking API: apps/deep-linking-api.md
    - Plugins:
      - Cordova PhoneGap Ionic: apps/cordova-phonegap-ionic.md
      - mParticle Android: apps/mparticle-android-v5.md
      - mParticle iOS: apps/mparticle-ios-v7.md
      - Titanium: apps/titanium.md
      - React Native: apps/react-native.md
      - Unity: apps/unity.md
      - Xamarin: apps/xamarin.md
    - 3rd Party SDKs & Plugins:
      - Adobe Launch Android SDK: apps/adobe-launch-android.md
      - Adobe Launch iOS SDK: apps/adobe-launch-ios.md
      - Adobe Launch Web Plugin: apps/adobe-launch-web-plugin.md
      - Segment Android SDK: apps/segment-android.md
      - Segment iOS SDK: apps/segment-ios.md
    - Validation Tools: resources/validation-tools.md
    - Launch your app:
      - Apple App Store: apps/ios-launch.md
      - Google Play: apps/android-launch.md
    - Advanced Configuration:
      - V2 Events: apps/v2event.md
    - Version Histories:
      - Android Version History: version-histories/android-version-history.md
      - iOS Version History: version-histories/ios-version-history.md
  - Marketing Channels:
    - Overview : resources/branch-channels.md
    - Website:
      - Overview: web/branch-web-solutions.md
      - Journeys App Banners: web/journeys.md
      - Journeys via AMP: web/amp-journeys.md
      - Deepviews: web/deep-views.md
      - Text Me the App: web/text-me-the-app.md
      - Hosted Deep Link Data: web/hosted-data.md
    - Paid ads:
      - Branch Universal Ads: deep-linked-ads/branch-universal-ads.md
      - Universal Ad Partners: deep-linked-ads/ad-networks-list.md
      - SAN Web Tracking: deep-linked-ads/san-web-tracking.md
      - Dynamic Product Feeds: deep-linked-ads/dynamic-product-feeds.md
    - Email:
      - Branch Universal Email: emails/universal-email.md
      - Universal Email Partners: emails/email-partners-list.md
      - Self Serve: emails/self-serve.md
    - SMS:
      - Vibes: sms/vibes.md
    - Push notifications: advance/push-notifications.md
    - Organic search:
      - Overview: organic-search/branch-organic-search.md
      - Firebase App Indexing: organic-search/firebase.md
      - Spotlight Search: organic-search/spotlight.md
      - General SEO Compatibility: organic-search/branch-seo.md
    - Viral & Referral:
      - Content sharing: viral/content-sharing.md
      - Referral programs: viral/referrals.md
    - New App Platforms:
      - Android Instant Apps: app-to-app/android-instant-apps.md
      - iMessage Apps: app-to-app/imessage-apps.md
  - Partner Management:
    - Overview: partner-management/branch-integrated-partners.md
    - Universal Ads Partners: deep-linked-ads/ad-networks-list.md
    - Universal Email Partners:
      - Active Campaign: emails/active-campaign.md
      - Adobe Campaign Classic: emails/adobe-campaign-classic.md
      - Adobe Campaign Standard: emails/adobe-campaign-standard.md
      - Amazon Simple Email Service: emails/amazon-ses.md
      - Betaout: emails/betaout.md
      - Blueshift: emails/blueshift.md
      - Braze (via SendGrid): emails/braze.md
      - Braze (via Mailjet): emails/braze-mailjet.md
      - Campaign Monitor: emails/campaign-monitor.md
      - Cheetah Digital Marketing Suite: emails/cheetah-digital-marketing-suite.md
      - CheetahMail: emails/cheetahmail.md
      - Epsilon: emails/epsilon.md
      - Emarsys: emails/emarsys.md
      - Hootsuite: social-links/hootsuite.md
      - IBM Watson Campaign Automation: emails/ibm-watson-campaign-automation.md
      - iCubesPro: emails/icubespro.md
      - Iterable: emails/iterable.md
      - Kahuna: emails/kahuna.md
      - Klaviyo: emails/klaviyo.md
      - Leanplum: emails/leanplum.md
      - Mailgun: emails/mailgun.md
      - Mailjet: emails/mailjet.md
      - Mailup: emails/mailup.md
      - Mandrill: emails/mandrill.md
      - Marketo: emails/marketo.md
      - MessageGears: emails/messagegears.md
      - MoEngage: emails/moengage.md
      - Oracle Bronto: emails/oracle-bronto.md
      - Oracle Eloqua: emails/oracle-eloqua.md
      - Oracle Responsys: emails/oracle-responsys.md
      - PostUp: emails/postup.md
      - Rapidmail: emails/rapidmail.md
      - Sailthru: emails/sailthru.md
      - Salesforce Marketing Cloud: emails/salesforce.md
      - Salesforce Marketing Cloud (Simplified): emails/salesforce_dns.md
      - Selligent Message Studio: emails/selligent.md
      - Sender: emails/sender.md
      - SendGrid: emails/sendgrid.md
      - Social Flow: social-links/social-flow.md
      - SparkPost: emails/sparkpost.md
      - Vero: emails/vero.md
      - WhatCounts: emails/whatcounts.md
      - Zeta: emails/zeta.md
    - Data Integration Partners:
      - 24Metrics Fraudshield: integrations/24metrics-fraudshield.md
      - Adjust: integrations/adjust.md
      - Adobe Analytics: integrations/adobe-analytics.md
      - Amplitude: integrations/amplitude.md
      - AppMetrica: integrations/appmetrica.md
      - Appsee: integrations/appsee.md
      - Appsflyer: integrations/appsflyer.md
      - Backinapp: integrations/backinapp.md
      - Braze: integrations/braze.md
      - CleverTap: integrations/clevertap.md
      - Convertro: integrations/convertro.md
      - Eulerian: integrations/eulerian.md
      - Fraud Defense: integrations/fraud-defense.md
      - Google Analytics: integrations/google-analytics.md
      - Kochava: integrations/kochava.md
      - Leanplum: integrations/leanplum.md
      - Localytics: integrations/localytics.md
      - Mixpanel: integrations/mixpanel.md
      - MobileAction: integrations/mobileaction.md
      - mParticle (export): integrations/mparticle.md
      - mParticle (import): integrations/mparticle-import.md
      - Segment (export): integrations/segment.md
      - Segment (import): integrations/segment-import.md
      - Singular: integrations/singular.md
      - TUNE: integrations/tune.md
      - WebEngage: integrations/webengage.md
    - Partner Resources:
      - Branch Certified Partner Program: partner-management/branch-certified-partner-program.md
      - Branch Partner Best Practices: partner-management/branch-partner-best-practices.md
      - Universal Ads Partner Integration QA Process: deep-linked-ads/universal-ads-partner-integration-qa-process.md
  - Reports & Analytics:
    - Overview: dashboard/analytics-overview.md
    - Cohort Analysis: dashboard/cohort-analysis.md
    - Paid Ads Analytics: activity-reports-analytics/paid-ads-analytics.md
    - Journeys Analytics: activity-reports-analytics/journeys-analytics.md
    - Link Level Analytics: activity-reports-analytics/link-level-analytics.md
    - Content Analytics: activity-reports-analytics/content-analytics.md
    - Liveview: exports/pba-liveview.md
  - Data Feeds:
    - Overview: exports/data-feeds-overview.md
    - Data Integrations: integrations/data-integrations-list.md
    - Webhooks: exports/ua-webhooks.md
    - Data Export API: exports/api-v3.md
    - Query API: exports/query-api.md
    - Supplemental Information:
      - Query Recipe Book: exports/query-recipe-book.md
      - Event Ontology: exports/event_ontology_data_schema.md
      - Export API Migration Guide: exports/export-api-migration-guide.md
      - Webhooks Migration Guide: exports/webhooks-migration-guide.md
    - Legacy Functionality:
      - Legacy Export API: exports/api.md
      - Legacy Webhooks: exports/webhooks.md
  - Translated Documentation:
    - Overview: translations/overview.md
    - 中文:
      - 配置控制面板: cn/integrate.md
    - 한국어:
      - Branch 연동 가이드 - iOS: kr/branch-ios.md
      - Branch 연동 가이드 - Android: kr/branch-android.md
      - Facebook 앱 인스톨 광고: kr/facebook-app-install-ads.md
      - iOS Universal Links: kr/universal-links.md
      - Android App Links 가이드: kr/android-app-links.md
      - 앱 내 딥링크 라우팅 가이드: kr/deep-link-routing.md
      - Facebook Ads FAQ (Korean): kr/facebook-ads-faq.md
