# Project information
site_name: 'Branch Documentation'
site_description: 'Branch Documentation for Deep Linking'
site_author: 'Branch'
site_url: 'https://ethanneff.github.io/branch-docs'

# Repository
repo_name: 'Branch Documentation'
repo_url: 'https://github.com/ethanneff/branch-docs'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2017 <a href="https://branch.io">Branch</a>'

# Files
theme: 'material'
theme_dir: 'src'
docs_dir: 'src/docs'
extra_css:
  - 'css/analytics.css'
  - 'css/main.css'

extra_javascript:
  # - 'js/analytics.js' #### need to fix white screen flash by moving js to head
  - 'js/main.js'

# Options
extra:
  # logo: 'img/logo.svg'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'globe'
      link: 'https://branch.io'
    - type: 'github'
      link: 'https://github.com/BranchMetrics/Documentation'
    - type: 'twitter'
      link: 'https://twitter.com/branchmetrics'
    - type: 'facebook'
      link: 'https://www.facebook.com/branchmetrics'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company-beta/3813083'
  disqus: 'branch-2'

# Extensions
markdown_extensions:
  - codehilite(linenums=true)
  - footnotes
  - toc(permalink=true)
  - meta
  - pymdownx.github
  - markdown_include.include

# Pages
pages:
  - Features: index.md
  - Getting started:
    - iOS: getting-started/ios.md
      # - Deep link into your app: getting-started/ios/deep-link.md
      # - Create links: getting-started/ios/create-link.md
      # - Share links: getting-started/ios/share-link.md
      # - Navigate to content: getting-started/ios/navigate-link.md
      # - Track custom events: getting-started/ios/track-event.md
      # - Track and refer users: getting-started/ios/track-user.md
      # - Track and publicize content: getting-started/ios/track-content.md
      # - Increase matching success: getting-started/ios/match-success.md
    - Android: getting-started/android.md
      # - Deep link into your app: getting-started/android/deep-link.md
      # - Create links: getting-started/android/create-link.md
      # - Share links: getting-started/android/share-link.md
      # - Navigate to content: getting-started/android/navigate-link.md
      # - Track custom events: getting-started/android/track-event.md
      # - Track and refer users: getting-started/android/track-user.md
      # - Track and publicize content: getting-started/android/track-content.md
      # - Increase matching success: getting-started/android/match-success.md
    - Adobe AIR: getting-started/adobe-air.md
      # - Deep link into your app: getting-started/air-ane/deep-link.md
      # - Create links: getting-started/air-ane/create-link.md
      # - Share links: getting-started/air-ane/share-link.md
      # - Navigate to content: getting-started/air-ane/navigate-link.md
      # - Track custom events: getting-started/air-ane/track-event.md
      # - Track and refer users: getting-started/air-ane/track-user.md
      # - Track and publicize content: getting-started/air-ane/track-content.md
      # - Increase matching success: getting-started/air-ane/match-success.md
    - Cordova PhoneGap Ionic: getting-started/cordova-phonegap-ionic.md
      # - Deep link into your app: getting-started/cordova-phonegap-ionic/deep-link.md
      # - Create links: getting-started/cordova-phonegap-ionic/create-link.md
      # - Share links: getting-started/cordova-phonegap-ionic/share-link.md
      # - Navigate to content: getting-started/cordova-phonegap-ionic/navigate-link.md
      # - Track custom events: getting-started/cordova-phonegap-ionic/track-event.md
      # - Track and refer users: getting-started/cordova-phonegap-ionic/track-user.md
      # - Track and publicize content: getting-started/cordova-phonegap-ionic/track-content.md
      # - Increase matching success: getting-started/cordova-phonegap-ionic/match-success.md
    - iMessage: getting-started/imessage.md
      # - Deep link into your app: getting-started/ios-imessage/deep-link.md
      # - Create links: getting-started/ios-imessage/create-link.md
      # - Share links: getting-started/ios-imessage/share-link.md
      # - Navigate to content: getting-started/ios-imessage/navigate-link.md
      # - Track custom events: getting-started/ios-imessage/track-event.md
      # - Track and refer users: getting-started/ios-imessage/track-user.md
      # - Track and publicize content: getting-started/ios-imessage/track-content.md
      # - Increase matching success: getting-started/ios-imessage/match-success.md
    - mParticle Android: getting-started/mparticle-android.md
      # - Deep link into your app: getting-started/mparticle-android/deep-link.md
      # - Create links: getting-started/mparticle-android/create-link.md
      # - Share links: getting-started/mparticle-android/share-link.md
      # - Navigate to content: getting-started/mparticle-android/navigate-link.md
      # - Track custom events: getting-started/mparticle-android/track-event.md
      # - Track and refer users: getting-started/mparticle-android/track-user.md
      # - Track and publicize content: getting-started/mparticle-android/track-content.md
      # - Increase matching success: getting-started/mparticle-android/match-success.md
      # - Deep link into your app: getting-started/titanium/deep-link.md
    - mParticle iOS: getting-started/mparticle-ios.md
      # - Deep link into your app: getting-started/mparticle-ios/deep-link.md
      # - Create links: getting-started/mparticle-ios/create-link.md
      # - Share links: getting-started/mparticle-ios/share-link.md
      # - Navigate to content: getting-started/mparticle-ios/navigate-link.md
      # - Track custom events: getting-started/mparticle-ios/track-event.md
      # - Track and refer users: getting-started/mparticle-ios/track-user.md
      # - Track and publicize content: getting-started/mparticle-ios/track-content.md
      # - Increase matching success: getting-started/mparticle-ios/match-success.md
    - Titanium: getting-started/titanium.md
      # - Create links: getting-started/titanium/create-link.md
      # - Share links: getting-started/titanium/share-link.md
      # - Navigate to content: getting-started/titanium/navigate-link.md
      # - Track custom events: getting-started/titanium/track-event.md
      # - Track and refer users: getting-started/titanium/track-user.md
      # - Track and publicize content: getting-started/titanium/track-content.md
      # - Increase matching success: getting-started/titanium/match-success.md
    - React Native: getting-started/react-native.md
      # - Deep link into your app: getting-started/react-native/deep-link.md
      # - Create links: getting-started/react-native/create-link.md
      # - Share links: getting-started/react-native/share-link.md
      # - Navigate to content: getting-started/react-native/navigate-link.md
      # - Track custom events: getting-started/react-native/track-event.md
      # - Track and refer users: getting-started/react-native/track-user.md
      # - Track and publicize content: getting-started/react-native/track-content.md
      # - Increase matching success: getting-started/react-native/match-success.md
    - Unity: getting-started/unity.md
      # - Deep link into your app: getting-started/unity/deep-link.md
      # - Create links: getting-started/unity/create-link.md
      # - Share links: getting-started/unity/share-link.md
      # - Navigate to content: getting-started/unity/navigate-link.md
      # - Track custom events: getting-started/unity/track-event.md
      # - Track and refer users: getting-started/unity/track-user.md
      # - Track and publicize content: getting-started/unity/track-content.md
      # - Increase matching success: getting-started/unity/match-success.md
    - Xamarin: getting-started/xamarin.md
      # - Deep link into your app: getting-started/xamarin/deep-link.md
      # - Create links: getting-started/xamarin/create-link.md
      # - Share links: getting-started/xamarin/share-link.md
      # - Navigate to content: getting-started/xamarin/navigate-link.md
      # - Track custom events: getting-started/xamarin/track-event.md
      # - Track and refer users: getting-started/xamarin/track-user.md
      # - Track and publicize content: getting-started/xamarin/track-content.md
      # - Increase matching success: getting-started/xamarin/match-success.md
  - Managing links:
    - Create links: managing-links/create-links.md
  - Converting web to app:
    - Deep Views: web-to-app/deep-views.md
    - Text me the app: web-to-app/text-me-the-app.md
    - Journeys: web-to-app/journeys.md
  - Converting ads to app:
    - Branch - Deep Link Feeds: ads-to-app/deep-link-feeds.md
    - Branch - App Install Ads: ads-to-app/app-install-ads.md
    - Google - App Installs: ads-to-app/google-app-installs.md
    - Google - Universal App Campaigns: ads-to-app/google-universal-app-campaigns.md
    - Google - Search Ads: ads-to-app/google-search.md
    - Facebook - App Installs: ads-to-app/facebook-app-installs.md
    - Facebook - App Engagement: ads-to-app/facebook-app-engagement.md
    - Facebook - Instagram: ads-to-app/facebook-instagram.md
    - Pinterets - App Installs: ads-to-app/pinterest-app-installs.md
    - Snapchat - App Installs: ads-to-app/snapchat-app-installs.md
  - Converting emails to app:
    - Responsys: emails-to-app/responsys.md
    - SFMC: emails-to-app/sfmc.md
    - SendGrid: emails-to-app/sendgrid.md
    - Sailthru: emails-to-app/sailthru.md
    - AppBoy: emails-to-app/appboy.md
    - Self Serve: emails-to-app/self-serve.md
  # - Convert Apps to App:
  #   - iOS Roots App: apps-to-app/ios-roots-app.md
  #   - iOS iMessage Apps: apps-to-app/ios-imessage-apps.md
  #   - Android Instant Apps: apps-to-app/android-instant-apps.md
  - Tracking analytics:
    - Growth: track-analytics/growth-attribution.md
    - User Value: track-analytics/user-value attribution.md
    - Revenue: track-analytics/revenue-attribution.md
  - Exporting analytics:
    - CSV Export: export-analytics/export-csv.md
    - Export API: export-analytics/export-api.md
    - Webhooks: export-analytics/export-webhooks.md
  - Integrating analytics:
    - Abobe Analytics: integrate-analytics/abobe-analytics.md
    - Adjust: integrate-analytics/adjust.md
    - Amplitude: integrate-analytics/amplitude.md
    - AppBoy: integrate-analytics/appboy.md
    - Google Analytics: integrate-analytics/google-analytics.md
    - Kochava: integrate-analytics/kochava.md
    - Localytics: integrate-analytics/localytics.md
    - Mixpanel: integrate-analytics/mixpanel.md
    - Tune: integrate-analytics/tune.md
    - AppMetrica: integrate-analytics/appmetrica.md