version: 2
jobs:
  build:
    working_directory: ~/docs
    environment:
      DC2: true
      BRANCH_STACK: python
    docker:
      - image: circleci/python:2.7.11
    steps:
      - checkout
      - setup_remote_docker
      - run: # install and activate virtual environment with pip
          command: |
            python -m venv venv
            . venv/bin/activate
      - run: pip install --upgrade pip
      - run: sudo pip install -r requirements.txt
      - run: mkdocs build --clean --verbose
      - save_cache:
          key: site
          paths:
            - ~/site
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

  deploy:
    machine: true
    working_directory: ~/docs
    environment:
      DC2: true
    steps:
      - checkout
      - restore_cache: # restore pip depedencies
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run: # install and activate virtual environment with pip
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - restore_cache:
          key: site
      - run: mkdocs gh-deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
