version: 2
jobs:
  build:
    machine: true
    working_directory: ~/docs
    steps:
      - checkout
      - run: pip install awscli --upgrade --user
      - run: pip install -r requirements.txt
      - run: mkdocs build --clean --verbose
      - run: export PATH=/home/circleci/.local/bin:$PATH
  deploy-staging:
    machine: true
    working_directory: ~/docs
    steps:
      - checkout
      - run: pip install awscli --upgrade --user
      - run: pip install -r requirements.txt
      - run: mkdocs build --clean --verbose
      - run:
          name: Deploy to S3
          command: aws s3 sync --delete ~/docs/site/ s3://staging.docs.branch.io
  deploy-production:
    machine: true
    working_directory: ~/docs
    steps:
      - checkout
      - run: pip install awscli --upgrade --user
      - run: pip install -r requirements.txt
      - run: mkdocs build --clean --verbose
      - run:
          name: Deploy to S3
          command: aws s3 sync --delete ~/docs/site/ s3://docs.branch.io
      - run:
          name: Clear CloudFront
          command: aws cloudfront create-invalidation --distribution-id E3L0JJHM8M3QTI --paths "/*"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - /staging-.*/
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - production
