version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.4

jobs:
  build:
    machine: true
    working_directory: ~/docs
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Build MkDocs
          command: mkdocs build --clean --verbose
      - persist_to_workspace:
          root: ~/docs
          paths:
            - site
  deploy-staging:
    parameters:
      staging-bucket:
        type: string
        default:
    machine: true
    working_directory: ~/docs
    steps:
      - attach_workspace:
          at: ~/docs
      - aws-s3/sync:
          from: ~/docs/site/
          to: << parameters.staging-bucket >>
          overwrite: true
  deploy-production:
    machine: true
    working_directory: ~/docs
    steps:
      - attach_workspace:
          at: ~/docs
      - aws-s3/sync:
          from: ~/docs/site/
          to: s3://docs.branch.io
          overwrite: true
      - run:
          name: Clear CloudFront
          command: aws cloudfront create-invalidation --distribution-id E3L0JJHM8M3QTI --paths "/*"

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy-production:
          requires:
            - build
          filters:
            branches:
              only:
                - production
      - deploy-staging:
          staging-bucket: s3://staging.docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - /staging-.*/
      - deploy-staging:
          staging-bucket: s3://staging2.docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - /staging2-.*/
      - deploy-staging:
          staging-bucket: s3://staging3.docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - /staging3-.*/
