version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.4

jobs:
  build:
    machine: true
    working_directory: ~/docs
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements.txt
      - run:
          name: Build MkDocs
          command: mkdocs build --clean --verbose
      - persist_to_workspace:
          root: ~/docs
          paths:
            - site
            - redirects.txt
  deploy-staging:
    parameters:
      s3-bucket:
        type: string
        default:
    machine: true
    working_directory: ~/docs
    steps:
      - attach_workspace:
          at: ~/docs
      - aws-s3/sync:
          from: ~/docs/site/
          to: << parameters.s3-bucket >>
          overwrite: true
      - run:
          name: Generate Redirects
          command: |
            touch index.html
            while read SOURCE; do
              IFS=' ' read -ra REDIRECTS \<<< "$SOURCE"
              echo "Redirecting ${REDIRECTS[0]} to ${REDIRECTS[1]}"
              aws s3 cp index.html << parameters.s3-bucket >>/${REDIRECTS[0]} --website-redirect ${REDIRECTS[1]}
            done < redirects.txt
            rm index.html
  deploy-production:
    parameters:
      s3-bucket:
        type: string
        default:
    machine: true
    working_directory: ~/docs
    steps:
      - attach_workspace:
          at: ~/docs
      - aws-s3/sync:
          from: ~/docs/site/
          to: << parameters.s3-bucket >>
          overwrite: true
      - run:
          name: Generate Redirects
          command: |
            touch index.html
            while read SOURCE; do
              IFS=' ' read -ra REDIRECTS \<<< "$SOURCE"
              echo "Redirecting ${REDIRECTS[0]} to ${REDIRECTS[1]}"
              aws s3 cp index.html << parameters.s3-bucket >>/${REDIRECTS[0]} --website-redirect ${REDIRECTS[1]}
            done < redirects.txt
            rm index.html
      - run:
          name: Clear CloudFront
          command: aws cloudfront create-invalidation --distribution-id E3L0JJHM8M3QTI --paths "/*"

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy-production:
          s3-bucket: s3://docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - production
      - deploy-staging:
          s3-bucket: s3://staging.docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - /staging-.*/
      - deploy-staging:
          s3-bucket: s3://staging2.docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - /staging2-.*/
      - deploy-staging:
          s3-bucket: s3://staging3.docs.branch.io
          requires:
            - build
          filters:
            branches:
              only:
                - /staging3-.*/
